### ISSUE TITLE
Reserve network id for GGX

### ISSUE THREAD

**Issue by akorchyn** [GoldenGateGGX/golden-gate#14]
#### Description ####
We need to book an ID for our chain to have a unique identifier related to our network.

ChainID is essential to the network, and we need to reserve it.

#### Definition of "Done" ####
We have reserved an identifier for our GGX network.

#### Suggested Solution ####
Make a pull request to https://github.com/satoshilabs/slips/blob/master/slip-0044.md , which contains a master list of registered coin types for BIP-0044

**Comment by xcthulhu** [comment]
Closed in https://github.com/satoshilabs/slips/pull/1516
