### ISSUE TITLE
Integration of XVM Pallet

### ISSUE THREAD

**Issue by FieldmanJR1** [GoldenGateGGX/golden-gate#6]
**Motivation**

##### Description #####

We need to integrate XVM pallet into our node runtime and check communication between smart-contracts.

##### Definition of "Done" #####

Developer can run local node and call the contract from both WASM and EVM environments.

**Comment by akorchyn** [comment]
I have compiled it with our node, and it finally compiles. Yooohooo. 
But yeah, for some reason, WASM contracts are not working yet. Going to investigate the issue...

**Comment by akorchyn** [comment]
I could manage to make a transaction from WASM to ETH virtual machine. The thing looks really promising, but unfortunately, in a current release, it doesn't support cross-vm querying

**Comment by akorchyn** [comment]
EVM to WASM works as well. Well, it's not that comfy to use as vice-versa, but still pretty promising. I need some time to polish my hacks and other stuff. And probably could publish a PR.
